# Inspired by https://github.com/timberio/vector-test-harness-github-actions-test-repo

name: Pretf

on:
  issue_comment:
    types: [created]

jobs:
  plan:

    runs-on: ubuntu-18.04

    if: |
      github.event_name == 'issue_comment' && github.event.action == 'created'
      && github.event.issue.pull_request != null
      && startsWith(github.event.comment.body, '/')

    steps:
    - name: acknowledge
      uses: actions/github-script@0.9.0
      with:
        github-token: '${{secrets.GITHUB_TOKEN}}'
        script: |
          github.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: "rocket"
          });

    - name: authorize
      uses: lannonbr/repo-permission-check-action@2.0.1
      with:
        permission: write
      env:
        GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'

    - name: checkout
      uses: actions/checkout@v2

    - name: pretf
      run: |
        echo $GITHUB_COMMENT
        echo $GITHUB_WORKSPACE
        pwd
        mkdir -p .direnv .docker/.direnv .docker/home
        echo $AWS_CREDENTIALS_FILE > /tmp/aws
        docker run --rm \
          -v $PWD:/src \
          -v $PWD/.docker/.direnv:/src/.direnv \
          -v $PWD/.docker/home:$HOME \
          -v /tmp/aws:/tmp/aws:ro \
          -e AWS_SHARED_CREDENTIALS_FILE=/tmp/aws \
          -v /etc/passwd:/etc/passwd:ro \
          -u $(id -u):$(id -g) \
          -w /src \
          claranet/direnv-asdf:latest \
          pretf github-action
        rm /tmp/aws
      env:
        GITHUB_COMMENT: '${{github.event.comment.body}}'

    - name: comment
      if: always()
      uses: actions/github-script@0.9.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        script: |
          const fs = require('fs');
          const { promisify } = require('util');
          const readFileAsync = promisify(fs.readFile);

          console.log(process.env);
          console.log(context);

          let output, body;
          try {
            output = await readFileAsync(`${process.env.GITHUB_WORKSPACE}/github-output`);
            body = `Action requested by ${context.payload.comment.html_url} is complete!\n\n${output}`;
          } catch {
            try {
              output = await readFileAsync(`${process.env.GITHUB_WORKSPACE}/github-error`);
              body = `Action requested by ${context.payload.comment.html_url} failed!\n\n${output}`;
            } catch {
              body = `Action requested by ${context.payload.comment.html_url} failed to run!`;
            }
          }
          body = `${body}\n\nYou can check the [execution log](${context.payload.repository.html_url}/actions/runs/${process.env.GITHUB_RUN_ID}) to learn more!`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });
